
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMBER = 10;
  public static final int BOOLEAN = 16;
  public static final int WRITE_CALL = 3;
  public static final int THEN = 5;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int OPERATOR = 13;
  public static final int IF = 4;
  public static final int TYPE = 14;
  public static final int OPAR = 8;
  public static final int ID = 12;
  public static final int error = 1;
  public static final int CPAR = 9;
  public static final int READ_CALL = 2;
  public static final int EQUALS = 6;
  public static final int END = 7;
  public static final int FLOAT = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "READ_CALL",
  "WRITE_CALL",
  "IF",
  "THEN",
  "EQUALS",
  "END",
  "OPAR",
  "CPAR",
  "NUMBER",
  "STRING",
  "ID",
  "OPERATOR",
  "TYPE",
  "FLOAT",
  "BOOLEAN"
  };
}

